services:
  # MySQL Database for Library System
  library-mysql:
    image: mysql:8.0
    container_name: library-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-library2024}
      MYSQL_DATABASE: library
      TZ: Asia/Seoul
    command:
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci
      --skip-character-set-client-handshake
      --init-connect='SET NAMES utf8mb4'
    volumes:
      - library_mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/01-init.sql
      - ./dummy_data.sql:/docker-entrypoint-initdb.d/02-dummy_data.sql
    ports:
      - "3307:3306"
    networks:
      - library-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${MYSQL_ROOT_PASSWORD:-library2024}"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Node.js Backend API Server
  library-backend:
    build: ./backend
    container_name: library-backend
    restart: unless-stopped
    env_file:
      - ./backend/.env
    ports:
      - "3001:3000"
    depends_on:
      library-mysql:
        condition: service_healthy
    networks:
      - library-network
    volumes:
      - ./backend:/app
      - /app/node_modules

networks:
  library-network:
    driver: bridge

volumes:
  library_mysql_data:
    driver: local