services:
  # MySQL Database for Library System
  library-mysql:
    image: mysql:8.0
    container_name: library-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-library2024}
      MYSQL_DATABASE: library
      MYSQL_CHARACTER_SET_SERVER: utf8mb4
      MYSQL_COLLATION_SERVER: utf8mb4_unicode_ci
      TZ: Asia/Seoul
    volumes:
      - library_mysql_data:/var/lib/mysql
    ports:
      - "3307:3306"  # Using 3307 to avoid conflict with existing MySQL on 3306
    networks:
      - library-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${MYSQL_ROOT_PASSWORD:-library2024}"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  library-network:
    driver: bridge

volumes:
  library_mysql_data:
    driver: local

